### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID 
GET https://contacts-api-sd5e.onrender.com/67cfbb23a1a7cbea81ddd015


### For testing after deployment
### Get all contacts - Production
GET https://contacts-api-sd5e.onrender.com/contacts

### Get contact by ID - Production
GET https://contacts-api-sd5e.onrender.com/contacts/67cfbb45a1a7cbea81ddd01f

